### PR TITLE
Adds timeouts to Image processor

### PR DESCRIPTION
**Pull request by mjgiarlo**

### CODE REVIEW

**Comment by cam156** [comment]
@mjgiarlo Test are failing

**Comment by mjgiarlo** [comment]
Dang.  I'll take a look soonish.

**Comment by cam156** [comment]
@mjgiarlo Figured out your issue here.  @jcoyne ready to merge?

**Comment by mjgiarlo** [comment]
:clap: 

Thanks, @cam156 @jcoyne

**Pull request merged**
